import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navBar";
import Footer from "@/components/footer";
import { ModalProvider } from "@/contexts/ModalContext";
import dynamic from "next/dynamic";

const ApolloWrapper = dynamic(() => import("@/app/apolloClient"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Straightforward Job Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative flex min-h-screen w-full flex-col overflow-x-hidden bg-cream">
        <ApolloWrapper>
          <ModalProvider>
            <NavBar />
            <main className="Main flex flex-1 flex-col">{children}</main>
            <Footer />
          </ModalProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
